services:
  smartsenseapi:
    image: anwar721/smartsense
    ports:
      - "8085:8085"  
    environment:
      SPRING_PROFILES_ACTIVE: prod 
      SPRING_JWT_TOKEN: ${JWT_TOKEN}
      SPRING_JWT_EXPIRATION: ${JWT_EXPIRATION}
      SPRING_MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - db
    networks:
      - smartsense-network

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - smartsense-network

    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--noauth"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
        - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
        ME_CONFIG_BASICAUTH: false
    depends_on:
        - db
    networks:
      - smartsense-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - smartsense-network

volumes:
  mongodb_data:
    name: mongodb_data
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  smartsense-network:
    name: smartsense-network